eliminated some functions, paramaterized install, allow for non-default skill directory, some error handling and quoting changes to appeas the shellcheck

diff --git a/msm/msm b/msm/msm
--- a/msm/msm
+++ b/msm/msm
@@ -23,103 +23,112 @@
 # This script assists in the installation and management of
 # skills loaded from Github.  
 
-mycroft_skill_folder="/opt/mycroft/skills"
-mycroft_virtualenv=~/.virtualenvs/mycroft/bin/activate
+mycroft_skill_folder=${mycroft_skill_folder:-"/opt/mycroft/skills"}
+if [[ ! -d "${mycroft_skill_folder}" ]] ; then
+    echo "Uname to access ${mycroft_skill_folder}!"
+    exit 101
+fi 
+
+default_skills="alarm audio-record configuration date-time desktop-launcher ip joke hello-world media npr-news naptime pairing personal reminder installer singing speak spelling stop stock volume weather wiki wolfram-alpha mark1-demo"
+
+# currently unused, so commented out.
+#mycroft_virtualenv=~/.virtualenvs/mycroft/bin/activate
 
 echo "#######  Mycroft Skill Manager #######"
 
 function help() {
-	echo "msm: Mycroft Skill Manager"
-	echo -e "     Copyright (c) 2017 Mycroft AI, Inc.  All rights reserved.\n"
-	echo "usage: msm install <repository> or <name>"
-	echo "     Installs the given Skill into the /opt/mycroft/skills directory"
-	echo "     where <repository> is the address of the skill in Github."
-	echo -e "example: msm install https://github.com/ethanaward/demo_skill.git\n"
-}
-
-function install() {
-        cd $mycroft_skill_folder
-	if [ -z "$2" ]; then
-		echo "You must pass the git url or skill name"
-		exit 1
-	fi
-	if [[ "$2" == "git@"* || "$2" == "https://"* || "$2" == "http://"* ]]; then
-		repo=$2
-	else
-		skill_list="`curl -s "https://raw.githubusercontent.com/MycroftAI/mycroft-skills/master/.gitmodules"`"
-		skills=`echo "$skill_list" | grep -n 'submodule' | sed 's/[[:space:]]//g' | sed 's/\[submodule"//g' | sed 's/"\]//g'`
-		exact_match=`echo "$skills" | grep -i ".*:$2$"`
-		skill=`echo "$skills" | grep -i ".*:.*$2.*"`
-		if [ ! -z $exact_match ]; then
-			skill=$exact_match
-		fi
-		git_line=`echo "$skill" | sed 's/\:.*//'`
-
-		if [[ $skill ==  *$'\n'* ]]; then
-			echo -e "Your search has multiple choices\n\n$skill" | sed 's/.*://g'
-			exit 2
-		else
-			if [ -z $git_line ]; then
-				echo "Skill not found"
-				exit 3
-			fi
-			repo_line=$(($git_line + 2))
-			repo=`echo "$skill_list" | sed -n $repo_line'{p;q;}' | sed 's/[[:space:]]//g' | sed 's/url=//g'`
-		fi 
-	fi
-	git_name=`echo "$repo" | sed 's/.*\///'`
-	name=`echo "$git_name" | sed 's/.git//'`
-        echo "Cloning repository"
-        git clone $repo >> /dev/null
-        cd $name
-         if [ -f "requirements.txt" ]; then
-         	echo "Installing libraries requirements"
-        	pip install -r requirements.txt
-        fi 
-        echo "Skill installed!"
-}
-
-function update() {
-        cd $mycroft_skill_folder
-	for d in $(ls -d */); do
-		if git -C "$d" rev-parse --git-dir > /dev/null 2>&1; then
-			cd $d
-			if [[ -z $(git status --porcelain) ]]; then
-				git fetch
-				git reset --hard origin/master 
-			fi
-			cd ..
-		fi
-	done
-}
-
-function install_defaults() {
-	skills=( "alarm" "audio-record" "configuration" "date-time" "desktop-launcher" "ip" "joke" "hello-world" "media" "npr-news" "naptime" "pairing" "personal" "reminder" "installer" "singing" "speak" "spelling" "stop" "stock" "volume" "weather" "wiki" "wolfram-alpha" "mark1-demo" )
-	for i in "${skills[@]}"
-	do
-		if [ ! -d "$mycroft_skill_folder/skill-$i" ]; then
-			install "" "https://github.com/MycroftAI/skill-$i.git"	
-		fi
-	done
-	update
-	echo "Installed!"
-	exit 0
+    echo "msm: Mycroft Skill Manager"
+    echo -e "     Copyright (c) 2017 Mycroft AI, Inc.  All rights reserved.\n"
+    echo "usage: msm install <repository> or <name>"
+    echo "     Installs the given Skill into the ${mycroft_skill_folder}"
+    echo "     where <repository> is the address of the skill in Github."
+    echo -e "example: msm install https://github.com/ethanaward/demo_skill.git\n"
+    exit 1
 }
 
 function list() {
-	curl -s "https://raw.githubusercontent.com/MycroftAI/mycroft-skills/master/.gitmodules" | grep 'submodule "' | sed 's/\[submodule "//g'| sed 's/"\]//g'
+	curl -s "https://raw.githubusercontent.com/MycroftAI/mycroft-skills/master/.gitmodules" 
 }
 
-if [ "$1" = "install" ]; then
-	install $*
-elif [ "$1" = "list" ]; then
-	echo -e "Searching...\n"
-	list 
-elif [ "$1" = "update" ]; then
-	update 
-elif [ "$1" = "default" ]; then
-	install_defaults 
-else
-	help
+function install() {
+if [[ $# -lt 1 ]] ; then
+    help
+    exit 1
 fi
+cd "${mycroft_skill_folder}"
 
+#if [[ -z "$1" ]]; then
+#    echo "You must pass the git url or skill name"
+#    exit 2
+#fi
+
+# loop through list of arguments
+while [[ $# -gt 0 ]] ; do
+    iskill="$1";
+    shift;
+    if [[ "${iskill}" == "git@"* || "${iskill}" == "https://"* || "${iskill}" == "http://"* ]]; then
+        repo="${iskill}"
+    else
+#        skill_list="$(curl -s "https://raw.githubusercontent.com/MycroftAI/mycroft-skills/master/.gitmodules")"
+        skill_list=$(list)
+        skills=$(echo "$skill_list" | grep -n 'submodule' | sed 's/[[:space:]]//g' | sed 's/\[submodule"//g' | sed 's/"\]//g')
+        exact_match=$(echo "$skills" | grep -i ".*:$2$")
+        skill=$(echo "$skills" | grep -i ".*:.*$2.*")
+        if [ ! -z "${exact_match}" ]; then
+            skill=${exact_match}
+        fi
+        git_line=$(echo "$skill" | sed 's/\:.*//')
+    
+        if [[ "${skill}" ==  *$'\n'* ]]; then
+            echo -e "Your search has multiple choices\n\n$skill" | sed 's/.*://g'
+            exit 3
+        else
+            if [[ -z "${git_line}" ]]; then
+                echo "Skill not found"
+                exit 3
+            fi
+        repo_line=$(($git_line + 2))
+        repo=$(echo "$skill_list" | sed -n $repo_line'{p;q;}' | sed 's/[[:space:]]//g' | sed 's/url=//g')
+        fi 
+    fi
+    git_name=$(echo "${repo}" | sed 's/.*\///')
+    name=$(echo "$git_name" | sed 's/.git//')
+    echo "Cloning repository"
+    git clone "${repo}" >> /dev/null
+    cd "${name}"
+    if [ -f "requirements.txt" ]; then
+        echo "Installing libraries requirements"
+        pip install -r requirements.txt
+    fi 
+    echo "Skill installed!"
+done
+
+}
+
+function update() {
+cd ${mycroft_skill_folder}
+for d in $(ls -d */); do
+    if git -C "$d" rev-parse --git-dir > /dev/null 2>&1; then
+        cd "${d}"
+        if [[ -z $(git status --porcelain) ]]; then
+        git fetch
+        git reset --hard origin/master 
+    fi
+    cd ..
+fi
+done
+}
+
+#### Main
+
+OPT=$1
+shift
+case ${OPT} in
+    "install") install "$*";;
+    "list") list | grep 'submodule "' | sed 's/\[submodule "//g'| sed 's/"\]//g' ;;
+    "update") update ;;
+    "default") install "${default_skills}" ;;
+    *) help ;;
+esac
+
+exit 0
