values from config

diff --git a/msm/msm b/msm/msm
--- a/msm/msm
+++ b/msm/msm
@@ -52,11 +52,35 @@ function help() {
   exit 1
 }
 
+SOURCE="${BASH_SOURCE[0]}"
+DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
+SYSTEM_CONFIG="$DIR/mycroft/configuration/mycroft.conf"
+
+function get_config_value() {
+  key="$1"
+  default="$2"
+  value="null"
+  for file in ~/.mycroft/mycroft.conf /etc/mycroft/mycroft.conf $SYSTEM_CONFIG;   do
+    if [[ -r $file ]] ; then
+        # remove comments in config for jq to work
+        # assume they may be preceded by whitespace, but nothing else
+        parsed="$( sed 's:^\s*//.*$::g' $file )"
+        echo "$parsed" >> "$DIR/mycroft/configuration/sys.conf"
+        value=$( jq -r "$key" "$DIR/mycroft/configuration/sys.conf" )
+        if [[ "${value}" != "null" ]] ;  then
+            rm -rf $DIR/mycroft/configuration/sys.conf
+            echo "$value"
+            return
+        fi
+    fi
+  done
+  echo "$default"
+}
+
+
 # Determine the platform
-mycroft_platform="null"
-if [[ -r /etc/mycroft/mycroft.conf ]] ; then
-   mycroft_platform=$( jq -r '.enclosure.platform' /etc/mycroft/mycroft.conf )
-else
+mycroft_platform="$(get_config_value '.enclosure.platform' 'null')"
+if [[ "${mycroft_platform}" == "null" ]] ; then
    if [[ "$(hostname)" == "picroft" ]] ; then
       mycroft_platform="picroft"
    elif [[ "$(hostname)" =~ "mark_1" ]] ; then
@@ -64,15 +88,7 @@ else
    fi
 fi
 
-# Get the location of the Skill folder
-mycroft_skill_folder="null"
-if [[ -r /etc/mycroft/mycroft.conf ]] ; then
-   mycroft_skill_folder=$( jq -r '.enclosure.skill_folder' /etc/mycroft/mycroft.conf )
-fi
-if [[ ${mycroft_skill_folder} == "null" ]] ; then
-   mycroft_skill_folder="/opt/mycroft/skills"
-fi
-
+mycroft_skill_folder="$(get_config_value '.skills.directory' '/opt/mycroft/skills')"
 if [[ ! -d "${mycroft_skill_folder}" ]] ; then
   echo "ERROR: Unable to find/access ${mycroft_skill_folder}!"
   exit 101
@@ -81,18 +97,23 @@ fi
 # Determine if on picroft/mk1?
 picroft_mk1="false"
 vwrap="true"
+use_virtualenvwrapper="$(get_config_value '.enclosure.use_virtualenvwrapper' 'true')"
 if [[ "${mycroft_platform}" == "picroft" ]] || [[ "${mycroft_platform}" == "mycroft_mark_1" ]] ; then
   picroft_mk1="true"
 else
-  if [[ -r /etc/bash_completion.d/virtualenvwrapper ]]; then
-    source /etc/bash_completion.d/virtualenvwrapper
-   elif [[ -r /usr/bin/virtualenvwrapper.sh ]]; then
-    source /usr/bin/virtualenvwrapper.sh
-  else
-    if locate virtualenvwrapper ; then
-      if ! source $(locate virtualenvwrapper) ; then
-        echo "WARNING: Unable to locate virtualenvwrapper.sh, not able to install skills!"
-        vwrap="false"
+  if [[ ${use_virtualenvwrapper} == "true" ]] ; then
+    if [[ -r /etc/bash_completion.d/virtualenvwrapper ]]; then
+      source /etc/bash_completion.d/virtualenvwrapper
+     elif [[ -r /usr/bin/virtualenvwrapper.sh ]]; then
+      source /usr/bin/virtualenvwrapper.sh
+     elif [[ -r /usr/bin/virtualenvwrapper ]]; then
+      source /usr/bin/virtualenvwrapper
+    else
+      if locate virtualenvwrapper ; then
+        if ! source $(locate virtualenvwrapper) ; then
+          echo "WARNING: Unable to locate virtualenvwrapper.sh, not able to install skills!"
+          vwrap="false"
+        fi
       fi
     fi
   fi
@@ -252,10 +273,11 @@ function install() {
   fi
 
   # TODO: Allow skipping virtualwrapper with an option?
-  if [[ "$vwrap" = "false" ]] ; then
-    echo "ERROR:  Missing virtualwrapper, cowardly refusing to install skills"
-    return 5
-  fi
+  #if [[ "$vwrap" = "false" ]] ; then
+  #  echo "ERROR:  Missing virtualwrapper, cowardly refusing to install
+  #skills"
+  #  return 5
+  #fi
 
   cd "${mycroft_skill_folder}"
 
@@ -363,7 +385,7 @@ function run_pip() {
     name=$*
     if [[ -f "requirements.txt" ]]; then
       echo "  Installing requirements..."
-      if [[ "${picroft_mk1}" == "false" ]]; then
+      if [[ "${picroft_mk1}" == "false" ]] || [[ ${use_virtualenvwrapper} == "true" ]] ; then
         if [[ "${VIRTUAL_ENV}" =~ .mycroft$ ]] ; then
           if ! pip install -r requirements.txt ; then
             echo "ERROR: Unable to install requirements for skill '${name}'"
