Add `msm info <skill>` command which displays information about a skill.

diff --git a/msm/msm b/msm/msm
--- a/msm/msm
+++ b/msm/msm
@@ -460,6 +460,77 @@ function update() {
   done
 }
 
+function print_info() {
+    str=$*
+    if [[ "${str}" == "git@"* || "${str}" == "https://"* || "${str}" == "http://"* ]]; then
+        # Repo was given
+        repo="${str}"
+    else
+        # Search for the given word(s) as the submodule
+        skills=$(echo "${LIST_CACHE}" | grep -n 'submodule' | sed 's/[[:space:]]//g' | sed 's/\[submodule"//g' | sed 's/"\]//g')
+
+        # Test for exact name match
+        exact_match=$(echo "$skills" | grep -i ".*:${str}$")
+        if [[ ! -z "${exact_match}" ]]; then
+            # Found a perfect match!
+            skill=${exact_match}
+        else
+            # Test for match of all supplied words/subwords
+            skill=$(echo "$skills")  # start with all skills
+            for s in ${str}
+            do
+                # whittle list down with each word in the search string
+                skill=$(echo "$skill" | grep -i ".*:.*${s}.*")
+            done
+        fi
+
+        git_line=$(echo "$skill" | sed 's/\:.*//')
+
+        if [[ "${skill}" ==  *$'\n'* ]]; then
+            # The str matches multiple skill repos, don't install
+            # due to ambiguity.
+            echo "Multiple matches for '${str}', be more specfic."
+            echo "------------------------------------------------------------"
+            echo "$skill" | sed 's/.*://g' | sort
+            echo "------------------------------------------------------------"
+            return 201
+        else
+            if [[ -z "${git_line}" ]]; then
+                echo "'${str}' skill was not found"
+            return 202
+            fi
+            repo_line=$(($git_line + 2))
+            repo=$(echo "${LIST_CACHE}" | sed -n $repo_line'{p;q;}' | sed 's/[[:space:]]//g' | sed 's/[[:space:]]//g' | sed 's/url=//g')
+        fi
+    fi
+    
+    local baseUrl=$(echo "${repo}/master/" | sed -e 's/github.com/raw.githubusercontent.com/g')
+    local readmeUrl="$baseUrl/readme.md"
+    local stat="$(curl -I -s $readmeUrl | sed -n '1p')"
+    local readme=""
+    if [[ $stat == *"200"* ]] ; then
+        readme="$(curl -s $readmeUrl)"
+    else
+        readmeUrl="$baseUrl/Readme.md"
+        stat=$(curl -I -s ${readmeUrl} | sed -n '1p')
+        if [[ $stat == *"200"* ]] ; then
+            readme="$(curl -s $readmeUrl)"
+        else
+            readmeUrl="$baseUrl/README.md"
+            stat=$(curl -I -s ${readmeUrl} | sed -n '1p')
+            if [[ $stat == *"200"* ]] ; then
+                readme="$(curl -s $readmeUrl)"
+            else
+                exit 404
+            fi
+        fi
+    fi
+
+    echo "$readme"
+    exit 0
+    
+}
+
 OPT=$1
 shift
 
@@ -602,6 +673,22 @@ case ${OPT} in
          help
          exit_code=1
       fi
+      ;;
+  "info")
+      get_skill_list
+      exit_code=$?
+      if [[ ${exit_code} -gt 0 ]] ; then
+          echo "${script}: error ${exit_code}"
+          exit ${exit_code}
+      fi
+      print_info $1
+      rc=$?
+      if [[ ${rc} -gt 0 ]] ; then
+          if [[ ${rc} -gt ${exit_code} ]] ; then
+              exit_code=${rc}
+          fi
+      fi
+      exit_code=0
       ;;
   *)
       help
